name: "Label merge Conflicts in PRs"
on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request:
    types: [synchronize]

jobs:
  label-merge-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "++Merge Conflict++"
          repoToken: "${{ secrets.MY_ACTION_TOKEN }}"
          commentOnDirty: "Auto Comment: Merge Conflict in Pull Request detected by automation."
       
