name: label-automation-on-close

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  automate-labels-close:
    runs-on: ubuntu-latest
    steps:
      - name: remove labels on close
        uses: upinetree/labeler@fix-pull-request-param
        with:
          remove-labels: "-- in Bearbeitung, ++draft PR++"
